package com.android.exchangerates.entities

import com.google.gson.annotations.SerializedName

data class Rates(
    @SerializedName("AMD") var amd: Rate,
    @SerializedName("AUD") var aud: Rate,
    @SerializedName("AZN") var azn: Rate,
    @SerializedName("BGN") var bgn: Rate,
    @SerializedName("BRL") var brl: Rate,
    @SerializedName("BYN") var byn: Rate,
    @SerializedName("CAD") var cad: Rate,
    @SerializedName("CHF") var chf: Rate,
    @SerializedName("CNY") var cny: Rate,
    @SerializedName("CZK") var czk: Rate,
    @SerializedName("DKK") var dkk: Rate,
    @SerializedName("EUR") var eur: Rate,
    @SerializedName("GBP") var gbp: Rate,
    @SerializedName("HKD") var hkd: Rate,
    @SerializedName("HUF") var huf: Rate,
    @SerializedName("INR") var inr: Rate,
    @SerializedName("JPY") var jpy: Rate,
    @SerializedName("KGS") var kgs: Rate,
    @SerializedName("KRW") var krw: Rate,
    @SerializedName("KZT") var kzt: Rate,
    @SerializedName("MDL") var mdl: Rate,
    @SerializedName("NOK") var nok: Rate,
    @SerializedName("PLN") var pln: Rate,
    @SerializedName("RON") var ron: Rate,
    @SerializedName("SEK") var sek: Rate,
    @SerializedName("SGD") var sgd: Rate,
    @SerializedName("TJS") var tjs: Rate,
    @SerializedName("TMT") var tmt: Rate,
    @SerializedName("TRY") var `try`: Rate,
    @SerializedName("UAH") var uah: Rate,
    @SerializedName("USD") var usd: Rate,
    @SerializedName("UZS") var uzs: Rate,
    @SerializedName("XDR") var xdr: Rate,
    @SerializedName("ZAR") var zar: Rate
) {
    fun getAll() = listOf(
        amd,
        aud,
        azn,
        bgn,
        brl,
        byn,
        cad,
        chf,
        cny,
        czk,
        dkk,
        eur,
        gbp,
        hkd,
        huf,
        inr,
        jpy,
        kgs,
        krw,
        kzt,
        mdl,
        nok,
        pln,
        ron,
        sek,
        sgd,
        tjs,
        tmt,
        `try`,
        uah,
        usd,
        uzs,
        xdr,
        zar
    )

    fun getAllCharCodes() = getAll().map { it.charCode }
}